spring:
  profiles:
    active: stage
  application:
    name: queue-management-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:24010/eureka/
  instance:
    preferIpAddress: true

server:
  port: 24031
  servlet:
    context-path: /queue-management

