spring:
  profiles:
    active: stage
  application:
    name: message-service
  cloud:
    function:
      definition: concertReservationPaymentConsumer;
    stream:
      kafka:
        default:
          consumer:
            autoCommitOffset: false
        binder:
          brokers:
            - localhost:9092
      bindings:
        concertReservationPaymentConsumer-in-0:
          destination: concert-reservation-payment
          group: concert-reservation-payment-group


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:24010/eureka/
  instance:
    preferIpAddress: true

server:
  port: 24201
  servlet:
    context-path: /message-service



custom-logging-filter:
  enabled: true


slack:
  message:
    polling:
      interval: 100







management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
