spring:
  profiles:
    active: stage
  application:
    name: redis-service



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:24010/eureka/
  instance:
    preferIpAddress: true

server:
  port: 24301
  servlet:
    context-path: /redis-service



custom-logging-filter:
  enabled: true
