server:
  port: 24000


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        ## queue-management-service
#        - id: queue-management-service
#          uri: lb://QUEUE-MANAGEMENT-SERVICE
#          predicates:
#            - Path=/queue-management/**
#          filters:
#            - RewritePath=/queue-management-service/(?<segment>.*), /$\{segment}
#        ## api-orchestration-service
#        - id: api-orchestration-service
#          uri: lb://API-ORCHESTRATION-SERVICE
#          predicates:
#            - Path=/api-orchestration/**
#          filters:
#            - RewritePath=/api-orchestration-service/(?<segment>.*), /$\{segment}
#
#
#      discovery:
#        locator:
#          enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:24010/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG