spring:
  profiles:
    active: stage
  application:
    name: payment-service
  cache:
    jcache:
      config: classpath:ehcache.xml


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:24010/eureka/
  instance:
    preferIpAddress: true

server:
  port: 24081
  servlet:
    context-path: /payment

custom:
  feign:
    direct:
      host:





custom-logging-filter:
  enabled: true



slack:
  channel:
    name: slack-test







management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
