spring:
  profiles:
    active: stage
  application:
    name: client-channel-service


server:
  port: 24101
  servlet:
    context-path: /client-channel


custom:
  feign:
    direct:
      host: http://localhost:24000/



custom-logging-filter:
  enabled: true



slack:
  channel:
    name: slack-test






management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
