spring:
  profiles:
    active: stage
  application:
    name: api-orchestration-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:24010/eureka/
  instance:
    preferIpAddress: true
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
          zkNodes: localhost:2181
      function:
        definition:
      bindings:
        concertReservationPaymentProducer-out-0:
          producer:
            destination: concert-reservation-payment
            contentType: application/json




server:
  port: 24051
  servlet:
    context-path: /api-orchestration

custom:
  feign:
    direct:
      host:


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true



feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 20
    time-to-live: 1
    time-to-live-unit: MINUTES
  okhttp:
    enabled: false



custom-logging-filter:
  enabled: false



slack:
  channel:
    name: slack-test
