spring:
  profiles:
    active: stage
  application:
    name: api-orchestration-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:24010/eureka/
  instance:
    preferIpAddress: true

server:
  port: 24051
  servlet:
    context-path: /api-orchestration

custom:
  feign:
    direct:
      host: