spring:
  profiles:
    active: stage
  application:
    name: reservation-service
  cache:
    jcache:
      config: classpath:ehcache.xml
  cloud:
    function:
      definition: concertReservationConfirmConsumer;
    stream:
      kafka:
        default:
          consumer:
            autoCommitOffset: false
        binder:
          brokers:
            - localhost:9092
      bindings:
        concertReservationConfirmConsumer-in-0:
          destination: concert-reservation-confirm
          group: reservation-self-group
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:24010/eureka/
  instance:
    preferIpAddress: true




server:
  port: 24071
  servlet:
    context-path: /reservation

custom:
  feign:
    direct:
      host:



custom-logging-filter:
  enabled: true



scheduler:
  temporalReservationExpireRate: 10000  # 1초마다 실행
  outboxResendRate: 5000  # 1초마다 실행



reservation:
  temporary:
    expire-seconds: 300


slack:
  channel:
    name: slack-test







management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
