spring:
  profiles:
    active: stage
  application:
    name: reservation-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:24010/eureka/
  instance:
    preferIpAddress: true

server:
  port: 24071
  servlet:
    context-path: /reservation

custom:
  feign:
    direct:
      host:



custom-logging-filter:
  enabled: true



scheduler:
  temporalReservationExpireRate: 1000  # 1초마다 실행



reservation:
  temporary:
    expire-seconds: 300


slack:
  channel:
    name: slack-test
